[package]
name = "chess"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "bridge"
crate-type = ["staticlib"]

[lints.rust]
unused = "allow"
unsafe_op_in_unsafe_fn = "allow"

[dependencies]
crossterm = "0.29.0"
tokio = { version = "1.49.0", features = ["full"]}